// src/app/layout.js

import { Manrope, Sora } from "next/font/google";
import "./globals.css";
import Footer from "./footer/Footer";
import Header from "./header/Header";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext"; 

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata = {
  title: "QuickBites",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${sora.variable} antialiased`}
      >
        <AuthProvider> 
          <CartProvider>
            <Header />
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
